# Generated by Django 3.2.15 on 2024-04-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240331_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationmodel',
            name='cgpa',
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='results',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
