# Generated by Django 3.2.15 on 2024-04-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20240402_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationmodel',
            name='results',
            field=models.CharField(blank=True, default='First Class', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workexperiencemodel',
            name='company',
            field=models.CharField(default='Caleb Mayaka', max_length=255),
        ),
    ]
